(source gnu)
(source melpa)
(source marmalade)

(depends-on "ag")

(depends-on "elscreen" :git "git@github.com:knu/elscreen.git")
(depends-on "git-gutter")
(depends-on "pbcopy")
(depends-on "popup")
(depends-on "popwin")
(depends-on "powerline")
(depends-on "quickrun")

;; input
(depends-on "auto-complete")
; (depends-on "tail")
(depends-on "yasnippet")
(depends-on "flycheck")

;; mini buffer
(depends-on "anything")
(depends-on "recentf-ext")
(depends-on "browse-kill-ring")
(depends-on "zlc")

;; Appearance
(depends-on "replace-colorthemes" :git "git@github.com:emacs-jp/replace-colorthemes.git")
(depends-on "rainbow-delimiters")
(depends-on "hlinum")

;; convert
(depends-on "json-reformat")

;; prog modes
(depends-on "coffee-mode")
(depends-on "go-mode")
(depends-on "js2-mode")
(depends-on "json-mode")
(depends-on "less-css-mode")
(depends-on "motion-mode")
(depends-on "puppet-mode")
(depends-on "haml-mode")
(depends-on "markdown-mode")
(depends-on "nginx-mode")
(depends-on "python-mode")
(depends-on "rhtml-mode")
(depends-on "rspec-mode")
(depends-on "ruby-mode")
(depends-on "sass-mode")
(depends-on "slim-mode")
(depends-on "yaml-mode")

(depends-on "rubocop")
(depends-on "ruby-block")
(depends-on "ruby-electric")
(depends-on "ruby-end")
(depends-on "robe")
(depends-on "inf-ruby")


(depends-on "go-autocomplete")
