#! /usr/bin/env ruby
# frozen_string_literal: true

require 'webrick'
require 'webrick/https'

dir = ARGV[0] || './'
port = (ARGV[1] || 8080).to_i
enable_ssl = (port == 8443)

WEBrick::HTTPServer.new(
  DocumentRoot: dir,
  Port: port,
  DirectoryIndex: %w[index.html],
  MimeTypes: WEBrick::HTTPUtils::DefaultMimeTypes.merge(
    # For DirectoryIndex
    # '' => 'text/html',
    'adoc' => 'text/asciidoc; charset=utf8',
    'md' => 'text/markdown; charset=utf8',
    'pu' => 'text/plantuml; charset=utf8',
  ),
  SSLEnable: enable_ssl,
  SSLCertName: [%w[CN localhost]],
).start
